"""renamed observed_for to observed_time column

Revision ID: 7459b3935fe7
Revises: fc2d1ec161e7
Create Date: 2024-12-08 00:40:46.907533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7459b3935fe7'
down_revision: Union[str, None] = 'fc2d1ec161e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_observations', sa.Column('observed_time', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('weather_observations', 'observed_for')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_observations', sa.Column('observed_for', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('weather_observations', 'observed_time')
    # ### end Alembic commands ###
