"""changed date fields

Revision ID: 76494d45ca27
Revises: 53c1a7e1cbbc
Create Date: 2024-12-05 17:21:25.403324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76494d45ca27'
down_revision: Union[str, None] = '53c1a7e1cbbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_observations', sa.Column('observed_for', sa.DateTime(), nullable=False))
    op.add_column('weather_observations', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('weather_observations', 'observed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_observations', sa.Column('observed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('weather_observations', 'created_at')
    op.drop_column('weather_observations', 'observed_for')
    # ### end Alembic commands ###
