"""added is_correct column

Revision ID: fc2d1ec161e7
Revises: c7f3b6f6ef12
Create Date: 2024-12-07 22:27:53.412774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc2d1ec161e7'
down_revision: Union[str, None] = 'c7f3b6f6ef12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_forecasts', sa.Column('is_correct', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_forecasts', 'is_correct')
    # ### end Alembic commands ###
