name: Deploy Weather Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Cache pip packages
        uses: actions/cache@v2
        with:
          path: ./package
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.prod.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Create deployment package
        run: |
          mkdir -p package
          pip install --platform manylinux2014_x86_64 --target ./package \
            --implementation cp --python-version 3.9 \
            --only-binary=:all: --upgrade \
            -r requirements.prod.txt
          rm -rf package/*.dist-info package/*.pth
          cp -r core database providers main.py ./package/
          cd package && zip -r ../deployment_package.zip . -x "*.pyc" "*.pyo" "test*" "tests*" "*__pycache__*"
          ls -lh ../deployment_package.zip

      - name: Terraform Init
        run: |
          cd infrastructure
          terraform init

      - name: Terraform Plan
        run: |
          cd infrastructure
          terraform plan \
            -var="database_url=${{ secrets.DATABASE_URL }}" \
            -var="nws_observation_api_token=${{ secrets.NWS_OBSERVATION_API_TOKEN }}" \
            -var="alert_email=${{ secrets.ALERT_EMAIL }}"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cd infrastructure
          terraform apply -auto-approve -var="database_url=${{ secrets.DATABASE_URL }}" -var="nws_observation_api_token=${{ secrets.NWS_OBSERVATION_API_TOKEN }}"
