name: Deploy Weather Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Cache pip packages
        uses: actions/cache@v2
        with:
          path: ./package
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.prod.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Create deployment package
        run: |
          mkdir -p package
          pip install --no-cache-dir --platform manylinux2014_x86_64 --target ./package \
            --implementation cp --python-version 3.9 \
            --only-binary=:all: --upgrade --force-reinstall \
            -r requirements.prod.txt
          ls -l ./package/requests*  # Verify that requests is installed
          rm -rf package/*.dist-info package/*.pth
          cp -r core database providers main.py ./package/
          cd package && zip -r ../deployment_package.zip . -x "*.pyc" "*.pyo" "test*" "tests*" "*__pycache__*"
          ls -lh ../deployment_package.zip

      - name: Terraform Init
        run: |
          cd infrastructure
          terraform init

      - name: Select Terraform Workspace
        run: |
          cd infrastructure
          terraform workspace select prod

      - name: Terraform Plan
        id: terraform_plan
        run: |
          cd infrastructure
          terraform plan -out=tfplan \
            -var="database_url=${{ secrets.DATABASE_URL }}" \
            -var="nws_observation_api_token=${{ secrets.NWS_OBSERVATION_API_TOKEN }}" \
            -var="alert_email=${{ secrets.ALERT_EMAIL }}" \
            -var="force_update_value=$(date '+%Y-%m-%dT%H:%M:%S')" > tf_plan.log 2>&1 || exit_code=$?
          cat tf_plan.log
          echo "exit_code=$exit_code" >> $GITHUB_ENV
          if [ "$exit_code" -eq 2 ]; then
            echo "Terraform detected changes."
          elif [ "$exit_code" -ne 0 ]; then
            echo "Terraform plan failed!" >&2
            exit $exit_code
          else
            echo "No changes detected by Terraform."
          fi

      - name: Terraform Apply
        if: env.exit_code == '2'
        run: |
          cd infrastructure
          terraform apply -auto-approve tfplan
